### ISSUE TITLE
EV car not displaying UI

### ISSUE THREAD

**Issue by SGT38** [ThatTonybo/BeamAdvisor#2]
When I use eSBR or Vivace E somehow the UI doesn't at all
![image](https://user-images.githubusercontent.com/104049646/164146009-1d369761-28f8-43a0-b2bb-547b2d222ed8.png)
![image](https://user-images.githubusercontent.com/104049646/164146061-6c67c4d2-c01b-49fc-a000-3d49eb1ab7f4.png)

On ICE varaint it work normally.
![image](https://user-images.githubusercontent.com/104049646/164146167-ac8dc42a-01c9-4119-bda6-7e40a3017069.png)

**Comment by ThatTonybo** [comment]
Interesting, that's an odd one.

Could you open the console (by default, your ` key) and see if there's any errors from beamadvisor/app.js?

**Comment by ThatTonybo** [comment]
Just tested on my end - I did have issues ranging between it hiding or partially working which is odd.

Tried it on another map though (Utah) and had no issues.

Can you also try on some other maps and see if it happens there. I got the eSBR 800 and Vivace qE running fine on Utah, but had some odd issues on Automation Playground.

**Comment by SGT38** [comment]
> pens there. I got the eSBR 800 and Vivace qE running fi

Just got some free time, I tested with other EV (qE & eSBR 800) and now in Utah and it still won't work for some reason. I also update to latest version. (Not sure if it's my end issue or not)

![image](https://user-images.githubusercontent.com/104049646/164981714-5e2de6ca-e1c4-49ae-a508-b446c12d44a7.png)
![image](https://user-images.githubusercontent.com/104049646/164981735-08cf9048-91a7-4bfc-81e5-6c1111168030.png)

**Comment by ThatTonybo** [comment]
Really odd for sure. I'll try do some more research into it and see if I can come up with some explanation for it happening.

**Comment by ThatTonybo** [comment]
Fixed in 1.3

The old "in vehicle" detection checked if there was watertemp present. If there wasn't, it considered you not in a vehicle. EVs don't have watertemp so that didn't work at all. The new system in 1.3 checks for gears instead, which functions.
