### ISSUE TITLE
UI not showing up at all

### ISSUE THREAD

**Issue by Wiimote24** [ThatTonybo/BeamAdvisor#5]
While trying out the BeamAdvisor UI, I accidentally right-clicked, resulting in the UI disappearing. Right-clicking on the bar again caused it to disappear as well.

I have tried reinstalling the mod, switching maps + vehicles, and restarting my computer. Not sure if this is what the mod is outputting to the console but I have this screenshot:

![Screenshot 2022-06-08 143020](https://user-images.githubusercontent.com/107153008/172720833-3aa5356d-75d5-48d4-a76c-1341dff1cdc5.png)

Edit: In addition, I have de-activated every other mod, to no avail.

**Comment by ThatTonybo** [comment]
The recent update introduced a way to hide the UI temporarily by right clicking on it (normal->GPS only->hidden). In the hidden mode, there should be a thin, transparent bar along the bottom edge of where the app was.

If you can't find it, go into the UI Apps section of the menu and move Beam Advisor all the way to a corner edge of the screen so the bar should be clickable blindly. If that doesn't work, there's another way which involves resetting the settings, I can explain that if you have more trouble.

**Comment by SANDOVAL2022** [comment]
Hello i have been trying to get the advisor but when i right clicked the black bar it dissapeared and it doesnt appear again

**Comment by Wiimote24** [comment]
Still not having any luck. How do I go about resetting the settings?

**Comment by ThatTonybo** [comment]
Open the CEF dev tools by hitting Ctrl+U, you should get a window like this:
![image](https://user-images.githubusercontent.com/28176227/173190222-da3f0c07-b081-4dcf-8c2e-12f1b4a14685.png)
On the top bar, click Application:
![image](https://user-images.githubusercontent.com/28176227/173190240-d5493d30-42d9-48aa-a9cc-b047e5bbefab.png)
Then on the side bar, expand Local Storage and click on local://local:
![image](https://user-images.githubusercontent.com/28176227/173190251-4920af5a-5e73-44cb-b15d-78160e471173.png)
Find the bar that says visibility:
![image](https://user-images.githubusercontent.com/28176227/173190269-ad401e2b-da29-4643-89ac-601b6073205e.png)
Double click where it says "hidden" and change it to "visible"

The last bit is important: Once you click off and it's set as visible, hit ALT+F4 to force quit out of BeamNG.
Then, reopen the game and it should be visible.

I'm working on a proper fix - namely making the bar that brings the app back less transparent.

**Comment by SANDOVAL2022** [comment]
> Open the CEF dev tools by hitting Ctrl+U, you should get a window like this: ![image](https://user-images.githubusercontent.com/28176227/173190222-da3f0c07-b081-4dcf-8c2e-12f1b4a14685.png) On the top bar, click Application: ![image](https://user-images.githubusercontent.com/28176227/173190240-d5493d30-42d9-48aa-a9cc-b047e5bbefab.png) Then on the side bar, expand Local Storage and click on local://local: ![image](https://user-images.githubusercontent.com/28176227/173190251-4920af5a-5e73-44cb-b15d-78160e471173.png) Find the bar that says visibility: ![image](https://user-images.githubusercontent.com/28176227/173190269-ad401e2b-da29-4643-89ac-601b6073205e.png) Double click where it says "hidden" and change it to "visible"
> 
> The last bit is important: Once you click off and it's set as visible, hit ALT+F4 to force quit out of BeamNG. Then, reopen the game and it should be visible.
> 
> I'm working on a proper fix - namely making the bar that brings the app back less transparent.

THX THX A LOT
