### ISSUE TITLE
2 bugs I found (I think)

### ISSUE THREAD

**Issue by salpaca53** [ThatTonybo/BeamAdvisor#6]
1. When I use a car with an automatic transmission, it still says 'manual' where it says 'Transmission Type'.

2. When I right click the ui app twice, it permanently turns invisible and I can't make it visible again even if I remove the ui app then put it back again. (I'm not entirely sure if this actually is a bug or not but I'm pretty sure it is. Please let me know if I'm wrong). Also I just discovered that somebody else has this "bug" too.

I can't provide any photos due to the second "bug".

**Comment by CarsonJSlane** [comment]
Problem 1 has already been talked about in this github post https://github.com/ThatTonybo/BeamAdvisor/issues/1 and has already been commentated.

Problem 2 has already been asked and is waiting to responded to https://github.com/ThatTonybo/BeamAdvisor/issues/5

Please look at other reports before making your own, to make sure that its not something that has already been bought up

**Comment by ThatTonybo** [comment]
#1 already exists as mentioned. To my knowledge, it's a BeamNG bug.

I've replied with a solution for your second concern in #5 but if the noted solution doesn't work for you either, let me know here.
